---
- name: Install software
  ansible.builtin.import_playbook: playbooks/install.yml

- name: generate local ssh keypair
  ansible.builtin.import_playbook: playbooks/generate_sshkey.yml

- name: create networks
  ansible.builtin.import_playbook: playbooks/vm_network.yml

- name: build vms
  ansible.builtin.import_playbook: playbooks/build_vms.yml

- name: deploy shell scripts for easy interact with vms
  ansible.builtin.import_playbook: playbooks/shell_scripts.yml

- name: Deploy docu 
  ansible.builtin.import_playbook: playbooks/deploy_doc.yml


#- name: Restart vms
#  import_playbook: playbooks/restart_vms.yml
