---
vm_image_path: /var/lib/libvirt/images
ssh_user: student
ssh_user_home: /home/{{ ssh_user }}/
force_generate_ssh_key: false
ssh_key_file_name: "{{ ssh_user_home }}/.ssh/vm"
virt_builder_customize_temp_file: /tmp/virt_builder_customize_file
vm_domain_name: local.example.com
vm_root_password: redhat

# training_type could be linux or ansible
training_type: linux

vm_networks:
  - name: local10_0_0_0
    file: ../files/local1000.xml
  - name: local10_0_1_0
    file: ../files/local1001.xml
  - name: local10_0_2_0
    file: ../files/local1002.xml

software_default:
  - git
  - virt-install
  - libvirt
  - cockpit-machines
  - virt-manager
  - qemu-kvm
  - wget
  - make
  - tar

software_centos_8:
  - libguestfs-tools
  - sshpass

software_centos_9:
  - guestfs-tools
  - sshpass

software_centos_10:
  - guestfs-tools
  - python3-paramiko

software: "{{ software_default + lookup('ansible.builtin.vars', 'software_centos_' + ansible_facts['distribution_version']) }}"
