---
- name: Build all vms
  hosts: all
  
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: create directory for images
      file:
        state: directory
        owner: root
        group: root
        mode: '00711'
        path: "{{ vm_image_path }}"

    - name: get existings vms
      community.libvirt.virt:
        command: list_vms
      register: existing_vms
      changed_when: false

    - name: build vm
      ansible.builtin.include_tasks: "../tasks/build_vms.inc.yml"
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm

    - name: Waiting for settle down before snapshot
      ansible.builtin.command:
        argv:
          - sleep
          - 60
      changed_when: false

    - name: do snapshot
      ansible.builtin.command:
        argv:
          - virsh
          - snapshot-create-as
          - --domain
          - "{{ vm.name }}"
          - --description
          - initial snapshot
          - --name
          - initial
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm
