---
- name: Build all vms
  hosts: all
  gather_facts: no
  
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: get existings vms
      community.libvirt.virt:
        command: list_vms
      register: existing_vms
      changed_when: false

    - name: build vm
      ansible.builtin.include_tasks: "../tasks/build_vms.inc.yml"
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm

    - name: waiting for settle down before snapshot
      ansible.builtin.pause:
        minutes: 1
        prompt: "Waiting for settle down before snapshot"

    - name: do snapshot
      ansible.builtin.command:
        argv:
          - virsh
          - snapshot-create-as
          - --domain
          - "{{ vm.name }}"
          - --description
          - initial snapshot
          - --name
          - initial
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm
