---
- name: Deploy some documentation
  hosts: all

  vars_files:
    - ../vars/vars.yml
    - ../vars/vms_{{ training_type }}.yml

  tasks:
    - name: Deploy the documentation
      ansible.builtin.template:
        src: "../templates/vm_doc.j2"
        dest: "{{ ssh_user_home }}/README"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0644'
