---
- name: generate ssh key 
  hosts: all

  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: create {{ ssh_user }} .ssh directory
      ansible.builtin.file:
        path: "{{ ssh_key_file_name | dirname }}"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0750'

    - name: generate ssh key pair
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_file_name }}"
        state: present
        force: "{{ force_generate_ssh_key | default(false, true) }}"

    - name: create ssh config file for {{ ssh_user }}
      ansible.builtin.template:
        src: ../templates/ssh_config.j2
        dest: "/{{ ssh_key_file_name | dirname }}/config"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0600'

