---
- name: install all software and start it
  hosts: all

  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Ensure the crb repository is enabled
      community.general.dnf_config_manager:
        name: crb
        state: enabled

    - name: Install EPEL packages
      ansible.builtin.dnf:
        name:
          - epel-releas
          - epel-next-release

    - name: install all for kvm
      ansible.builtin.yum:
        name: "{{ software }}"
        state: present
        
    - name: start virtualization
      ansible.builtin.systemd:
        name: libvirtd.service
        enabled: yes
        state: started

    - name: start cockpit
      ansible.builtin.systemd:
        name: cockpit.socket
        enabled: yes
        state: started

    - name: extend path with /usr/local/bin in sudoers file
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        backrefs: yes
        regexp: "^(Defaults\\s+secure_path\\s*=\\s*.+(?<!\\/usr\\/local\\/bin))$"
        line: "\\1:/usr/local/bin"

    - name: Add {{ ssh_user }} to libvirt group
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        groups: 
          - libvirt
          - wheel
        append: yes
