---
- name: Deploy the shell scripts
  hosts: all

  vars_files:
    - ../vars/vars.yml
    - ../vars/vms_{{ training_type }}.yml

  tasks:
    - name: Copy the scripts
      ansible.builtin.template:
        src: "{{ script }}"
        dest: "/usr/local/bin/{{ script | basename }}"
        owner: root
        group: root
        mode: '0755'
      with_fileglob:
        - ../templates/scripts/*.sh
      loop_control:
        loop_var: script
